INSERT INTO burgers (burger_name) VALUES ('PHILLY CHEESEBURGER');
INSERT INTO burgers (burger_name) VALUES ('BACON DOUBLE CHEEEBURGER');
INSERT INTO burgers (burger_name) VALUES ('ORIGINAL ONION BURGER');